[package]
name = "tide-openidconnect"
version = "0.1.0"
authors = ["Michael Alyn Miller <malyn@strangeGizmo.com>"]
edition = "2018"
publish = false

[dependencies]
openidconnect = "2.0.1"
serde = "1.0.125"
tide = { version = "0.16.0", default-features = false, features = ["cookies"] }

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
tide-testing = "0.1"
